# Generated by Django 4.2.8 on 2024-01-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='pro_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
