# Generated by Django 4.2.7 on 2024-01-18 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
